services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ig-audio-bot
    restart: unless-stopped
    shm_size: '1gb'
    env_file:
      - .env
    volumes:
      - ./cookies.txt:/app/cookies.txt
      - bot-data:/app/data
    tmpfs:
      - /tmp:size=1G,mode=1777

volumes:
  bot-data:
